# Generated by Django 4.0.3 on 2022-04-08 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Material Class',
                'verbose_name_plural': 'Material Classes',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('kc_1_1', models.FloatField(verbose_name='kc 1.1 (N/mm²)')),
                ('mc', models.FloatField(verbose_name='Mc')),
                ('material_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='material.materialclass')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
