# Generated by Django 4.0.3 on 2022-04-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='type',
            field=models.CharField(choices=[('ENDMILL', 'Endmill')], default='ENDMILL', max_length=10),
        ),
    ]
