# Generated by Django 4.0.3 on 2022-04-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_library', '0003_alter_tool_material_alter_tool_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='material',
            field=models.CharField(choices=[('HSS', 'HSS'), ('CARBIDE', 'Carbide')], default='CARBIDE', max_length=10),
        ),
        migrations.AlterField(
            model_name='tool',
            name='type',
            field=models.CharField(choices=[('ENDMILL', 'Endmill')], default='ENDMILL', max_length=10),
        ),
    ]
