# Generated by Django 4.0.3 on 2022-04-08 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tool_library', '0001_initial'),
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuttingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fz_base', models.FloatField(help_text='fz at ae=0.5d and ap=1d', verbose_name='fz (base)')),
                ('vc_base', models.FloatField(help_text='vc at ae=0.5d and ap=1d', verbose_name='vc (base)')),
                ('fz_factor_slotting', models.FloatField(default=1.0, help_text='fz factor for slotting operations', verbose_name='fz factor slotting')),
                ('vc_factor_slotting', models.FloatField(default=1.0, help_text='vc factor for slotting operations', verbose_name='vc factor slotting')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.material')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool_library.tool')),
            ],
            options={
                'verbose_name': 'Cutting Data',
                'verbose_name_plural': 'Cutting Data',
                'ordering': ('material', 'tool'),
            },
        ),
        migrations.CreateModel(
            name='CuttingRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_max_rpm_override', models.PositiveIntegerField(blank=True, null=True, verbose_name='Max spindle RPM override')),
                ('machine_max_vf_override', models.FloatField(blank=True, null=True, verbose_name='Max cutting speed override')),
                ('tool_fz_override', models.FloatField(blank=True, null=True, verbose_name='fz override')),
                ('tool_vc_override', models.FloatField(blank=True, null=True, verbose_name='vc override')),
                ('ae', models.FloatField(blank=True, null=True, verbose_name='ae (mm)')),
                ('ap', models.FloatField(blank=True, null=True, verbose_name='ap (mm)')),
                ('phi_selection', models.CharField(blank=True, choices=[('C', 'Center'), ('OC', 'Off Center')], max_length=2, null=True)),
                ('cutting_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milling.cuttingdata')),
            ],
            options={
                'verbose_name': 'Cutting Recipe',
                'verbose_name_plural': 'Cutting Recipies',
            },
        ),
        migrations.CreateModel(
            name='JobTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('coolant_mode', models.CharField(choices=[('MIST', 'Mist'), ('FLOOD', 'Flood')], default='MIST', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('spindle_net_power_kw', models.FloatField(verbose_name='Spindle net power (kW)')),
                ('max_rpm', models.PositiveIntegerField(verbose_name='Max spindle RPM (1/min)')),
                ('max_vf', models.FloatField(verbose_name='Max cutting speed (mm/min)')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ToolAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('tool_pocket', models.PositiveIntegerField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='milling.jobtemplate')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milling.cuttingrecipe')),
            ],
        ),
        migrations.AddField(
            model_name='jobtemplate',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milling.machine'),
        ),
        migrations.AddField(
            model_name='jobtemplate',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.material'),
        ),
        migrations.AddField(
            model_name='cuttingrecipe',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milling.machine'),
        ),
    ]
