# Generated by Django 5.2.4 on 2025-07-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("milling", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobtemplate",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
