# Generated by Django 4.0.3 on 2022-04-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milling', '0003_alter_jobtemplate_coolant_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtemplate',
            name='coolant_mode',
            field=models.CharField(choices=[('MIST', 'Mist'), ('FLOOD', 'Flood')], default='MIST', max_length=10),
        ),
    ]
